#!/usr/bin/env python3
"""Post a four-pass review to a GitHub pull request as inline comments.

Creates ONE pull-request review (event COMMENT, never approve/request-changes)
whose body is the merged summary and whose inline comments are the findings,
each anchored at its file and line on the PR's head commit. Findings that
point at lines GitHub cannot anchor (not part of the diff) are listed in the
review body instead, so nothing is dropped.

Usage:
  post-review.py --pr 142 --findings findings.json --summary summary.md [--dry-run]
  post-review.py --pr 142 --findings findings.json --summary summary.md --mode summary

  --mode inline   (default) one review with inline comments
  --mode summary  one ordinary PR comment containing the whole report
  --dry-run       print the payload and the anchoring report; post nothing
  --repo o/r      override the owner/repo (defaults to the PR's URL)

findings.json is a list of objects:
  {
    "id": "COR-1",                  required
    "title": "Export crashes ...",  required
    "severity": "critical|major|minor",
    "confidence": 92,
    "pass": "correctness",
    "path": "app/Services/InvoiceExporter.php",   required (repo-relative)
    "line": 48,                     required (line number in the head version)
    "end_line": 50,                 optional (multi-line range, same hunk)
    "body": "why it matters / evidence",
    "fix": "concrete suggestion"
  }

summary.md is the review body (the merged report header and pass summaries).

Requires an authenticated `gh` CLI. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field

FOOTER = "Generated by four-pass-review (Claude Code)"
HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


# --------------------------------------------------------------------------
# Diff parsing
# --------------------------------------------------------------------------

@dataclass
class FileLines:
    right: set[int] = field(default_factory=set)   # commentable, head side
    left: set[int] = field(default_factory=set)    # commentable, base side (deleted)
    hunks: list[tuple[int, int]] = field(default_factory=list)  # right-side ranges


def parse_diff(diff_text: str) -> dict[str, FileLines]:
    """Return, per file path, the line numbers GitHub will accept for comments."""
    files: dict[str, FileLines] = {}
    current: FileLines | None = None
    path: str | None = None
    old_no = new_no = 0
    in_hunk = False
    hunk_start = 0

    for raw in diff_text.splitlines():
        if raw.startswith("diff --git "):
            current, path, in_hunk = None, None, False
            continue
        if raw.startswith("+++ "):
            target = raw[4:].strip()
            if target == "/dev/null":
                path = None
            else:
                path = target[2:] if target.startswith("b/") else target
                current = files.setdefault(path, FileLines())
            continue
        if raw.startswith("--- "):
            continue
        m = HUNK_RE.match(raw)
        if m:
            old_no = int(m.group(1))
            new_no = int(m.group(3))
            in_hunk = True
            hunk_start = new_no
            if current is not None:
                current.hunks.append((hunk_start, hunk_start + int(m.group(4) or 1) - 1))
            continue
        if not in_hunk or current is None:
            continue
        if raw.startswith("\\"):  # "\ No newline at end of file"
            continue
        if raw.startswith("+"):
            current.right.add(new_no)
            new_no += 1
        elif raw.startswith("-"):
            current.left.add(old_no)
            old_no += 1
        else:  # context line (starts with space) or empty
            current.right.add(new_no)
            current.left.add(old_no)
            new_no += 1
            old_no += 1
    return files


def _normalise_path(p: str) -> str:
    p = p.strip().strip("`")
    if p.startswith("./"):
        p = p[2:]
    return p


# --------------------------------------------------------------------------
# Payload building
# --------------------------------------------------------------------------

def _comment_body(f: dict) -> str:
    meta = " · ".join(x for x in [
        f.get("severity"),
        f"confidence {f['confidence']}" if f.get("confidence") is not None else None,
        f.get("pass"),
    ] if x)
    parts = [f"**[{f['id']}] {f['title']}**" + (f"\n{meta}" if meta else "")]
    if f.get("body"):
        parts.append(str(f["body"]).strip())
    if f.get("fix"):
        parts.append(f"**Suggested fix:** {str(f['fix']).strip()}")
    return "\n\n".join(parts)


def _same_hunk(fl: FileLines, start: int, end: int) -> bool:
    return any(a <= start and end <= b for a, b in fl.hunks)


def build_review(findings: list[dict], summary: str, diff_files: dict[str, FileLines],
                 commit_id: str) -> tuple[dict, list[dict]]:
    """Return (payload, unanchored_findings)."""
    comments: list[dict] = []
    unanchored: list[dict] = []
    for f in findings:
        for key in ("id", "title", "path", "line"):
            if key not in f:
                raise ValueError(f"finding missing required field '{key}': {f}")
        path = _normalise_path(str(f["path"]))
        line = int(f["line"])
        fl = diff_files.get(path)
        if fl is None:
            unanchored.append(f)
            continue
        entry: dict = {"path": path, "body": _comment_body(f)}
        end_line = f.get("end_line")
        if line in fl.right:
            entry["side"] = "RIGHT"
            if end_line and int(end_line) > line and int(end_line) in fl.right \
                    and _same_hunk(fl, line, int(end_line)):
                entry["start_line"], entry["start_side"] = line, "RIGHT"
                entry["line"] = int(end_line)
            else:
                entry["line"] = line
        elif line in fl.left:
            entry["side"], entry["line"] = "LEFT", line
        else:
            unanchored.append(f)
            continue
        comments.append(entry)

    body = summary.rstrip() + "\n"
    if unanchored:
        body += "\n### Findings outside the diff (not anchorable inline)\n\n"
        for f in unanchored:
            body += (f"- **[{f['id']}]** `{_normalise_path(str(f['path']))}:{f['line']}` — "
                     f"{f['title']}")
            meta = " · ".join(x for x in [f.get("severity"), f.get("pass")] if x)
            body += f" ({meta})" if meta else ""
            body += "\n"
            if f.get("fix"):
                body += f"  - Fix: {str(f['fix']).strip()}\n"
    body += f"\n{FOOTER}\n"

    payload = {"commit_id": commit_id, "event": "COMMENT", "body": body, "comments": comments}
    return payload, unanchored


# --------------------------------------------------------------------------
# gh plumbing
# --------------------------------------------------------------------------

def gh(*args: str, input_text: str | None = None) -> str:
    proc = subprocess.run(["gh", *args], input=input_text, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args)} failed ({proc.returncode}):\n{proc.stderr.strip()}")
    return proc.stdout


def pr_info(pr: str, repo: str | None) -> tuple[str, str, str]:
    """Return (owner/repo, head sha, html url)."""
    args = ["pr", "view", pr, "--json", "headRefOid,url,state"]
    if repo:
        args += ["--repo", repo]
    data = json.loads(gh(*args))
    if data.get("state", "OPEN") != "OPEN":
        raise RuntimeError(f"PR {pr} is {data.get('state')}; refusing to post a review")
    url = data["url"]
    m = re.match(r"https?://[^/]+/([^/]+/[^/]+)/pull/\d+", url)
    owner_repo = repo or (m.group(1) if m else None)
    if not owner_repo:
        raise RuntimeError(f"could not determine owner/repo from {url}; pass --repo")
    return owner_repo, data["headRefOid"], url


def pr_diff(pr: str, repo: str | None) -> str:
    args = ["pr", "diff", pr]
    if repo:
        args += ["--repo", repo]
    return gh(*args)


def post_review(owner_repo: str, pr: str, payload: dict) -> dict:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        json.dump(payload, tmp)
        tmp_path = tmp.name
    try:
        out = gh("api", "--method", "POST", f"repos/{owner_repo}/pulls/{pr}/reviews",
                 "--input", tmp_path)
    finally:
        os.unlink(tmp_path)
    return json.loads(out)


def post_summary_comment(pr: str, repo: str | None, body: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as tmp:
        tmp.write(body)
        tmp_path = tmp.name
    try:
        args = ["pr", "comment", pr, "--body-file", tmp_path]
        if repo:
            args += ["--repo", repo]
        return gh(*args).strip()
    finally:
        os.unlink(tmp_path)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pr", required=True, help="pull request number")
    ap.add_argument("--findings", required=True, help="path to findings.json")
    ap.add_argument("--summary", required=True, help="path to summary.md (review body)")
    ap.add_argument("--mode", choices=["inline", "summary"], default="inline")
    ap.add_argument("--repo", help="owner/repo override")
    ap.add_argument("--dry-run", action="store_true", help="print payload, post nothing")
    args = ap.parse_args(argv)

    with open(args.findings, encoding="utf-8") as fh:
        findings = json.load(fh)
    if not isinstance(findings, list):
        print("findings.json must be a JSON list", file=sys.stderr)
        return 2
    with open(args.summary, encoding="utf-8") as fh:
        summary = fh.read()

    if args.mode == "summary":
        body = summary.rstrip() + "\n\n" + "\n".join(
            f"- **[{f['id']}]** `{_normalise_path(str(f['path']))}:{f['line']}` — {f['title']}"
            for f in findings) + f"\n\n{FOOTER}\n"
        if args.dry_run:
            print(body)
            return 0
        print(post_summary_comment(args.pr, args.repo, body))
        return 0

    owner_repo, head_sha, url = pr_info(args.pr, args.repo)
    diff_files = parse_diff(pr_diff(args.pr, args.repo))
    payload, unanchored = build_review(findings, summary, diff_files, head_sha)

    print(f"PR: {url} @ {head_sha[:10]}", file=sys.stderr)
    print(f"inline comments: {len(payload['comments'])}; in body only: {len(unanchored)}",
          file=sys.stderr)
    for f in unanchored:
        print(f"  not anchorable: [{f['id']}] {f['path']}:{f['line']}", file=sys.stderr)

    if args.dry_run:
        print(json.dumps(payload, indent=2))
        return 0

    try:
        result = post_review(owner_repo, args.pr, payload)
    except RuntimeError as e:
        if "422" in str(e) and payload["comments"]:
            # GitHub rejected an anchor we thought was valid; post everything in the body.
            print(f"inline anchoring rejected ({e}); retrying as body-only review", file=sys.stderr)
            fallback_payload, _ = build_review([], summary, {}, head_sha)
            fallback_payload["body"] = payload["body"].replace(f"\n{FOOTER}\n", "") + \
                "\n### Findings\n\n" + "\n".join(
                    f"- {c['path']}:{c.get('line')} — " + c["body"].splitlines()[0]
                    for c in payload["comments"]) + f"\n\n{FOOTER}\n"
            result = post_review(owner_repo, args.pr, fallback_payload)
        else:
            raise
    print(result.get("html_url", url))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, ValueError, OSError, json.JSONDecodeError) as exc:
        print(f"post-review: {exc}", file=sys.stderr)
        sys.exit(1)
