#!/usr/bin/env python3
"""Post a four-pass review to a GitHub pull request as inline comments.

Creates ONE pull-request review whose body is the merged summary, whose inline
comments are the findings (each anchored at its file and line on the PR's head
commit), and whose event follows the report's verdict. Findings that point at
lines GitHub cannot anchor (not part of the diff) are listed in the review body
instead, so nothing is dropped.

The verdict decides the review event, on one question: does this block the
merge?

  PASS              no findings at all      -> APPROVE
  PASS_WITH_NOTES   only minor findings     -> APPROVE (nits, non-blocking)
  REQUEST_CHANGES   at least one major      -> REQUEST_CHANGES
  FAIL              at least one critical   -> REQUEST_CHANGES
  INCOMPLETE        a pass did not report   -> COMMENT (not a verdict)

A verdict we cannot read falls back to COMMENT, which neither approves nor
blocks. APPROVE and REQUEST_CHANGES are real, visible actions. GitHub refuses
both on your own pull request; the script then posts the same review as a
COMMENT and says so, rather than failing.

Usage:
  post-review.py --pr 142 --findings findings.json --summary summary.md [--dry-run]
  post-review.py --pr 142 --findings findings.json --summary summary.md --mode summary

  --mode inline   (default) one review with inline comments
  --mode summary  one ordinary PR comment containing the whole report
  --verdict X     override the verdict; default reads it from summary.md
  --dry-run       print the payload and the anchoring report; post nothing
  --repo o/r      override the owner/repo (defaults to the PR's URL)
  --on-existing   what to do when this tool already reviewed this PR:
                  replace (default) supersedes the earlier review, skip
                  leaves the PR alone, add posts anyway
  --diff-file F   read the diff from a file rather than `gh pr diff`; with
  --head-sha SHA  this, a --dry-run needs no network and no auth
  --last-reviewed print the head sha this tool last reviewed on this PR and
                  exit; exits 1 with no output when there is none. Feeds an
                  incremental re-review (`/review <n> --since last`).

Re-running is expected: review, push fixes, review again. By default an
earlier review from this tool is superseded (its body is blanked and its
inline comments deleted) so the PR does not collect duplicates. A submitted
review cannot be deleted through the API; a --mode summary comment is an
ordinary issue comment and is edited in place instead. The footer records
which commit was reviewed, and superseding preserves it, so --last-reviewed
can still answer what has already been covered.

findings.json is a list of objects in the finding contract, defined by
finding.schema.json beside this script and checked before anything is posted:
  {
    "id": "COR-1",                  required
    "title": "Export crashes ...",  required
    "severity": "critical|major|minor",   required
    "confidence": 92,               required (0-100)
    "pass": "correctness",          required
    "path": "app/Services/InvoiceExporter.php",   required (repo-relative)
    "line": 48,                     required (line number in the head version)
    "end_line": 50,                 optional (multi-line range, same hunk)
    "side": "LEFT",                 optional; LEFT means `line` is a base-version
                                    line, for findings about deleted code
    "body": "why it matters / evidence",   required
    "fix": "concrete suggestion",   optional
    "suggestion": "replacement text",       optional; rendered as a GitHub
                                    ```suggestion block so the author can commit
                                    it in one click. Replaces exactly the
                                    anchored line range, and is dropped for
                                    LEFT-side and unanchored findings, which
                                    GitHub cannot apply a suggestion to.
  }

summary.md is the review body (the merged report header and pass summaries).

Requires an authenticated `gh` CLI. Standard library only.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import tempfile
from dataclasses import dataclass, field

# The finding contract sits beside this script. Nothing puts this directory on
# sys.path when the script is run by absolute path or loaded by the tests.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from finding_contract import validate as validate_findings  # noqa: E402

FOOTER = "Generated by four-pass-review (Claude Code)"
# The footer records which commit was reviewed, so a re-review can ask what it
# already covered and review only what has landed since. `FOOTER` stays a
# prefix of it, so the prior-review match is unchanged.
REVIEWED_RE = re.compile(r"reviewed at ([0-9a-f]{7,40})")


def footer_line(head_sha: str | None = None) -> str:
    return f"{FOOTER} · reviewed at {head_sha}" if head_sha else FOOTER


def last_reviewed_sha(reviews: list[dict], login: str) -> str | None:
    """The head this tool last reviewed on this PR, newest first."""
    for review in reversed(find_prior_reviews(reviews, login, include_superseded=True)):
        m = REVIEWED_RE.search(review.get("body") or "")
        if m:
            return m.group(1)
    return None
HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")
UNANCHORED_HEADING = "Findings outside the diff (not anchorable inline)"
FALLBACK_HEADING = "Findings (inline anchoring was rejected by GitHub)"
SUMMARY_HEADING = "Findings"

# The verdict decides the review event, on one question: does this block the
# merge? Minor findings are nits, so they approve, the way a human reviewer
# approves with comments.
VERDICT_EVENTS = {
    "PASS": "APPROVE",
    "PASS_WITH_NOTES": "APPROVE",
    "REQUEST_CHANGES": "REQUEST_CHANGES",
    "FAIL": "REQUEST_CHANGES",
    # A pass that failed to run has not said "nothing wrong"; it has said
    # nothing. That must not approve a pull request, and it is not grounds to
    # block one either, so it comments.
    "INCOMPLETE": "COMMENT",
}
DEFAULT_EVENT = "COMMENT"
VERDICT_RE = re.compile(r"^\*\*Verdict:\*\*\s*\**\s*([A-Z_]+)", re.M)
# GitHub refuses APPROVE and REQUEST_CHANGES on your own pull request.
SELF_REVIEW_MARKER = "your own pull request"


def verdict_from_summary(summary: str) -> str | None:
    """The `**Verdict:** X` value from the report header, when it is one we know."""
    m = VERDICT_RE.search(summary)
    verdict = m.group(1) if m else None
    return verdict if verdict in VERDICT_EVENTS else None


def event_for_verdict(verdict: str | None) -> str:
    """The GitHub review event for a verdict; COMMENT when it is unknown."""
    return VERDICT_EVENTS.get(verdict or "", DEFAULT_EVENT)


# --------------------------------------------------------------------------
# Diff parsing
# --------------------------------------------------------------------------

@dataclass
class FileLines:
    right: set[int] = field(default_factory=set)   # commentable, head side
    left: set[int] = field(default_factory=set)    # commentable, base side (deleted)
    hunks: list[tuple[int, int]] = field(default_factory=list)  # right-side ranges


def parse_diff(diff_text: str) -> dict[str, FileLines]:
    """Return, per file path, the line numbers GitHub will accept for comments."""
    files: dict[str, FileLines] = {}
    current: FileLines | None = None
    path: str | None = None
    old_no = new_no = 0
    in_hunk = False
    hunk_start = 0

    for raw in diff_text.splitlines():
        if raw.startswith("diff --git "):
            current, path, in_hunk = None, None, False
            continue
        # "+++ "/"--- " are file headers only outside a hunk; inside one they are
        # ordinary added/deleted content lines whose text starts with "++ "/"-- ".
        if not in_hunk and raw.startswith("+++ "):
            target = _unquote_diff_path(raw[4:].strip())
            if target == "/dev/null":
                path = None
            else:
                path = target[2:] if target.startswith("b/") else target
                current = files.setdefault(path, FileLines())
            continue
        if not in_hunk and raw.startswith("--- "):
            continue
        m = HUNK_RE.match(raw)
        if m:
            old_no = int(m.group(1))
            new_no = int(m.group(3))
            in_hunk = True
            hunk_start = new_no
            if current is not None:
                current.hunks.append((hunk_start, hunk_start + int(m.group(4) or 1) - 1))
            continue
        if not in_hunk or current is None:
            continue
        if raw.startswith("\\"):  # "\ No newline at end of file"
            continue
        if raw.startswith("+"):
            current.right.add(new_no)
            new_no += 1
        elif raw.startswith("-"):
            current.left.add(old_no)
            old_no += 1
        else:  # context line (starts with space) or empty
            current.right.add(new_no)
            current.left.add(old_no)
            new_no += 1
            old_no += 1
    return files


# Git quotes a path containing non-ASCII or control characters, C-style, with
# the UTF-8 bytes as octal escapes: `+++ "b/caf\303\251.py"`. Left as-is the
# quotes and escapes become part of the path, it never matches a finding, and
# every finding on such a file silently falls out of the inline comments into
# the "outside the diff" list. (`core.quotePath=false` turns this off, but the
# script cannot rely on the caller's git config.)
_OCTAL = "01234567"
_C_ESCAPES = {"a": 7, "b": 8, "f": 12, "n": 10, "r": 13, "t": 9, "v": 11,
              '"': 34, "\\": 92}


def _unquote_diff_path(p: str) -> str:
    if len(p) < 2 or not (p.startswith('"') and p.endswith('"')):
        return p
    inner, out, i = p[1:-1], bytearray(), 0
    while i < len(inner):
        c = inner[i]
        if c == "\\" and i + 1 < len(inner):
            nxt = inner[i + 1]
            if nxt in _OCTAL and len(inner) >= i + 4:
                try:
                    out.append(int(inner[i + 1:i + 4], 8))
                    i += 4
                    continue
                except ValueError:
                    pass
            if nxt in _C_ESCAPES:
                out.append(_C_ESCAPES[nxt])
                i += 2
                continue
        out.extend(c.encode("utf-8"))
        i += 1
    return out.decode("utf-8", "replace")


def _normalise_path(p: str) -> str:
    p = p.strip().strip("`")
    if p.startswith("./"):
        p = p[2:]
    return p


# --------------------------------------------------------------------------
# Payload building
# --------------------------------------------------------------------------

def _comment_body(f: dict, allow_suggestion: bool = False) -> str:
    meta = " · ".join(x for x in [
        f.get("severity"),
        f"confidence {f['confidence']}" if f.get("confidence") is not None else None,
        f.get("pass"),
    ] if x)
    parts = [f"**[{f['id']}] {f['title']}**" + (f"\n{meta}" if meta else "")]
    if f.get("body"):
        parts.append(str(f["body"]).strip())
    if f.get("fix"):
        parts.append(f"**Suggested fix:** {str(f['fix']).strip()}")
    # A `suggestion` block turns the finding into a commit the author can apply
    # in one click. GitHub only honours it on an inline comment anchored to the
    # head side, so it is dropped everywhere else rather than rendered as a
    # fenced block that does nothing.
    if allow_suggestion and f.get("suggestion") is not None:
        parts.append("```suggestion\n" + str(f["suggestion"]).rstrip("\n") + "\n```")
    return "\n\n".join(parts)


def _body_bullet(f: dict) -> str:
    """Render one finding as a review-body bullet (no trailing newline)."""
    text = f"- **[{f['id']}]** `{_normalise_path(str(f['path']))}:{f['line']}` — {f['title']}"
    meta = " · ".join(x for x in [f.get("severity"), f.get("pass")] if x)
    if meta:
        text += f" ({meta})"
    if f.get("fix"):
        text += f"\n  - Fix: {str(f['fix']).strip()}"
    return text


def _findings_section(heading: str, findings: list[dict]) -> str:
    """Render a '### heading' block of body bullets, or '' when there is nothing to list."""
    if not findings:
        return ""
    return f"\n### {heading}\n\n" + "\n".join(_body_bullet(f) for f in findings) + "\n"


def _check_required(f: dict) -> None:
    """Raise ValueError if a finding lacks a field every output path needs."""
    for key in ("id", "title", "path", "line"):
        if key not in f:
            raise ValueError(f"finding missing required field '{key}': {f}")


def _same_hunk(fl: FileLines, start: int, end: int) -> bool:
    return any(a <= start and end <= b for a, b in fl.hunks)


def _anchor(f: dict, fl: FileLines) -> dict | None:
    """Return the side/line fields for an inline comment, or None if GitHub cannot anchor it."""
    line = int(f["line"])
    if str(f.get("side", "RIGHT")).upper() == "LEFT":
        # `line` is a base-version number; only ever anchor it on the LEFT side.
        return {"side": "LEFT", "line": line} if line in fl.left else None
    if line not in fl.right:
        return None
    end_line = int(f.get("end_line") or 0)
    if end_line > line and end_line in fl.right and _same_hunk(fl, line, end_line):
        return {"side": "RIGHT", "start_side": "RIGHT", "start_line": line, "line": end_line}
    return {"side": "RIGHT", "line": line}


def build_review(findings: list[dict], summary: str, diff_files: dict[str, FileLines],
                 commit_id: str, heading: str = UNANCHORED_HEADING,
                 event: str = DEFAULT_EVENT) -> tuple[dict, list[dict]]:
    """Return (payload, unanchored_findings); `heading` titles the body section for the latter."""
    comments: list[dict] = []
    unanchored: list[dict] = []
    for f in findings:
        _check_required(f)
        path = _normalise_path(str(f["path"]))
        fl = diff_files.get(path)
        anchor = _anchor(f, fl) if fl is not None else None
        if anchor is None:
            unanchored.append(f)
            continue
        on_head = anchor.get("side") == "RIGHT"
        comments.append({"path": path, "body": _comment_body(f, allow_suggestion=on_head),
                         **anchor})

    body = (summary.rstrip() + "\n" + _findings_section(heading, unanchored)
            + f"\n{footer_line(commit_id)}\n")
    payload = {"commit_id": commit_id, "event": event, "body": body, "comments": comments}
    return payload, unanchored


def build_summary_body(findings: list[dict], summary: str,
                       head_sha: str | None = None) -> str:
    """Return the single-comment report used by --mode summary (every finding as a body bullet)."""
    for f in findings:
        _check_required(f)
    return (summary.rstrip() + "\n" + _findings_section(SUMMARY_HEADING, findings)
            + f"\n{footer_line(head_sha)}\n")


# --------------------------------------------------------------------------
# gh plumbing
# --------------------------------------------------------------------------

# --------------------------------------------------------------------------
# Previous runs
# --------------------------------------------------------------------------
#
# Re-reviewing is the normal case: review, push fixes, review again. Without
# this the PR collects a new review and a duplicate set of inline comments
# every time. GitHub will not let a submitted review be deleted, so "replace"
# means supersede: blank the old review's body, drop its inline comments, then
# post the new one. A `--mode summary` comment is an issue comment, which can
# be edited in place, so that case is a true update.

SUPERSEDED_NOTE = "_Superseded by a newer four-pass review._"


def find_prior_reviews(reviews: list[dict], login: str,
                       include_superseded: bool = False) -> list[dict]:
    """Reviews this tool posted as `login`: our footer, and ours to edit.

    `login` is required, not optional. Superseding deletes inline comments,
    which cannot be undone, so a review is only ever a candidate when we can
    prove whose it is. Matching on the footer alone would mean that a failed
    `gh api user` call is enough to start deleting another account's comments.
    """
    out = []
    for r in reviews:
        body = r.get("body") or ""
        if FOOTER not in body:
            continue
        if SUPERSEDED_NOTE in body and not include_superseded:
            continue
        if (r.get("user") or {}).get("login") != login:
            continue
        out.append(r)
    return out


def find_prior_comment(comments: list[dict], login: str) -> dict | None:
    """The most recent issue comment this tool posted as `login`, if any."""
    ours = [c for c in comments
            if FOOTER in (c.get("body") or "")
            and (c.get("user") or {}).get("login") == login]
    return ours[-1] if ours else None


def unknown_login_warning(action: str) -> str:
    return (f"could not confirm the authenticated account (`gh api user` failed); "
            f"not {action} an earlier review. Leaving a duplicate is better than "
            f"editing or deleting something we cannot prove is ours.")


def stale_comment_ids(review_comments: list[dict], review_ids: set[int]) -> list[int]:
    """Inline comments belonging to the given reviews."""
    return [c["id"] for c in review_comments
            if c.get("pull_request_review_id") in review_ids and "id" in c]


def gh(*args: str, input_text: str | None = None) -> str:
    proc = subprocess.run(["gh", *args], input=input_text, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError(f"gh {' '.join(args)} failed ({proc.returncode}):\n{proc.stderr.strip()}")
    return proc.stdout


def pr_info(pr: str, repo: str | None,
            require_open: bool = True) -> tuple[str, str, str]:
    """Return (owner/repo, head sha, html url)."""
    args = ["pr", "view", pr, "--json", "headRefOid,url,state"]
    if repo:
        args += ["--repo", repo]
    data = json.loads(gh(*args))
    if require_open and data.get("state", "OPEN") != "OPEN":
        raise RuntimeError(f"PR {pr} is {data.get('state')}; refusing to post a review")
    url = data["url"]
    m = re.match(r"https?://[^/]+/([^/]+/[^/]+)/pull/\d+", url)
    owner_repo = repo or (m.group(1) if m else None)
    if not owner_repo:
        raise RuntimeError(f"could not determine owner/repo from {url}; pass --repo")
    return owner_repo, data["headRefOid"], url


def pr_diff(pr: str, repo: str | None) -> str:
    args = ["pr", "diff", pr]
    if repo:
        args += ["--repo", repo]
    return gh(*args)


def post_review(owner_repo: str, pr: str, payload: dict) -> dict:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        json.dump(payload, tmp)
        tmp_path = tmp.name
    try:
        out = gh("api", "--method", "POST", f"repos/{owner_repo}/pulls/{pr}/reviews",
                 "--input", tmp_path)
    finally:
        os.unlink(tmp_path)
    return json.loads(out)


def post_review_with_fallbacks(owner_repo: str, pr: str, payload: dict, findings: list[dict],
                              summary: str, head_sha: str) -> dict:
    """Post the review, degrading when GitHub refuses the event or an anchor."""
    for _ in range(3):
        try:
            return post_review(owner_repo, pr, payload)
        except RuntimeError as e:
            text = str(e)
            if SELF_REVIEW_MARKER in text.lower() and payload["event"] != DEFAULT_EVENT:
                print(f"GitHub refused a {payload['event']} review on your own PR; "
                      f"posting the same review as a {DEFAULT_EVENT}", file=sys.stderr)
                payload["event"] = DEFAULT_EVENT
                continue
            if "422" in text and payload["comments"]:
                # GitHub rejected an anchor we thought was valid; post everything
                # in the body. An empty diff map makes every finding unanchored.
                print(f"inline anchoring rejected ({text}); retrying as body-only review",
                      file=sys.stderr)
                payload, _ = build_review(findings, summary, {}, head_sha,
                                          heading=FALLBACK_HEADING, event=payload["event"])
                continue
            raise
    raise RuntimeError("gave up posting the review after retrying")


def gh_json(*args: str):
    """A `gh api` call whose output is JSON. Returns [] when the call fails."""
    try:
        return json.loads(gh(*args) or "[]")
    except (RuntimeError, json.JSONDecodeError) as e:
        print(f"could not read {args[-1]}: {e}", file=sys.stderr)
        return []


def current_login() -> str | None:
    """The authenticated user, used to avoid touching someone else's review."""
    try:
        return gh("api", "user", "--jq", ".login").strip() or None
    except RuntimeError:
        return None


def supersede_reviews(owner_repo: str, pr: str, reviews: list[dict]) -> None:
    """Blank out earlier reviews from this tool and delete their inline comments.

    Best effort throughout: a PR we cannot tidy is still a PR we should post
    the new review to, so every failure here warns and continues.
    """
    by_id = {r["id"]: r for r in reviews if "id" in r}
    if not by_id:
        return
    comments = gh_json("api", "--paginate", f"repos/{owner_repo}/pulls/{pr}/comments")
    for comment_id in stale_comment_ids(comments, set(by_id)):
        try:
            gh("api", "--method", "DELETE",
               f"repos/{owner_repo}/pulls/comments/{comment_id}")
        except RuntimeError as e:
            print(f"could not delete stale comment {comment_id}: {e}", file=sys.stderr)
    for review_id in sorted(by_id):
        # Keep the `reviewed at <sha>` marker: it is how a later run works out
        # what has already been covered. Blanking it would make every
        # re-review start from scratch.
        old_body = by_id[review_id].get("body") or ""
        m = REVIEWED_RE.search(old_body)
        try:
            gh("api", "--method", "PUT",
               f"repos/{owner_repo}/pulls/{pr}/reviews/{review_id}",
               "-f", f"body={SUPERSEDED_NOTE}\n\n{footer_line(m.group(1) if m else None)}")
        except RuntimeError as e:
            print(f"could not supersede review {review_id}: {e}", file=sys.stderr)


def update_summary_comment(owner_repo: str, comment_id: int, body: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False) as tmp:
        json.dump({"body": body}, tmp)
        tmp_path = tmp.name
    try:
        out = gh("api", "--method", "PATCH",
                 f"repos/{owner_repo}/issues/comments/{comment_id}", "--input", tmp_path)
    finally:
        os.unlink(tmp_path)
    return json.loads(out).get("html_url", "")


def post_summary_comment(pr: str, repo: str | None, body: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False) as tmp:
        tmp.write(body)
        tmp_path = tmp.name
    try:
        args = ["pr", "comment", pr, "--body-file", tmp_path]
        if repo:
            args += ["--repo", repo]
        return gh(*args).strip()
    finally:
        os.unlink(tmp_path)


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pr", required=True, help="pull request number")
    ap.add_argument("--findings", help="path to findings.json")
    ap.add_argument("--summary", help="path to summary.md (review body)")
    ap.add_argument("--mode", choices=["inline", "summary"], default="inline")
    ap.add_argument("--verdict", choices=sorted(VERDICT_EVENTS),
                    help="override the verdict; by default it is read from summary.md")
    ap.add_argument("--repo", help="owner/repo override")
    ap.add_argument("--on-existing", choices=["replace", "skip", "add"], default="replace",
                    help="what to do when this tool already reviewed this PR "
                         "(default: replace, which supersedes the earlier review)")
    ap.add_argument("--diff-file", help="read the diff from a file instead of `gh pr diff` "
                                        "(with --head-sha, makes --dry-run work offline)")
    ap.add_argument("--head-sha", help="head commit for --diff-file dry runs")
    ap.add_argument("--last-reviewed", action="store_true",
                    help="print the head sha this tool last reviewed on this PR "
                         "and exit; exits 1 with no output when there is none")
    ap.add_argument("--dry-run", action="store_true", help="print payload, post nothing")
    args = ap.parse_args(argv)
    if not args.last_reviewed and not (args.findings and args.summary):
        ap.error("--findings and --summary are required unless --last-reviewed is given")

    if args.last_reviewed:
        owner_repo, _, _ = pr_info(args.pr, args.repo, require_open=False)
        login = current_login()
        if login is None:
            print(unknown_login_warning("reading"), file=sys.stderr)
            return 1
        sha = last_reviewed_sha(
            gh_json("api", "--paginate", f"repos/{owner_repo}/pulls/{args.pr}/reviews"),
            login)
        if not sha:
            print(f"no earlier four-pass review found on PR {args.pr}", file=sys.stderr)
            return 1
        print(sha)
        return 0

    with open(args.findings, encoding="utf-8") as fh:
        findings = json.load(fh)
    # Refuse before anything reaches GitHub: a finding with no body or a
    # severity off the scale would post as a broken comment, in public.
    errors = validate_findings(findings)
    if errors:
        for e in errors:
            print(f"findings.json: {e}", file=sys.stderr)
        print("findings.json breaks the finding contract (finding.schema.json); "
              "nothing posted", file=sys.stderr)
        return 2
    with open(args.summary, encoding="utf-8") as fh:
        summary = fh.read()

    verdict = args.verdict or verdict_from_summary(summary)
    event = event_for_verdict(verdict)

    # A dry run against a saved diff touches no network, so the documented
    # "dry-run first" step works offline and in tests.
    offline = bool(args.dry_run and args.diff_file and args.head_sha)
    if offline:
        owner_repo, head_sha, url = (args.repo or "OWNER/REPO"), args.head_sha, "(offline)"
    else:
        # Both modes refuse to post to a PR that is not open.
        owner_repo, head_sha, url = pr_info(args.pr, args.repo)

    if args.mode == "summary":
        body = build_summary_body(findings, summary, head_sha)
        prior_comment = None
        if not offline and args.on_existing != "add":
            login = current_login()
            if login is None:
                print(unknown_login_warning("updating"), file=sys.stderr)
            else:
                comments = gh_json("api", "--paginate",
                                   f"repos/{owner_repo}/issues/{args.pr}/comments")
                prior_comment = find_prior_comment(comments, login)
        if prior_comment and args.on_existing == "skip":
            print(f"already commented: "
                  f"{prior_comment.get('html_url', prior_comment.get('id'))}; "
                  "nothing posted (--on-existing skip)", file=sys.stderr)
            return 0
        if args.dry_run:
            if prior_comment:
                print(f"would update comment {prior_comment.get('id')}", file=sys.stderr)
            print(body)
            return 0
        if prior_comment:
            print(update_summary_comment(owner_repo, prior_comment["id"], body))
            return 0
        print(post_summary_comment(args.pr, args.repo, body))
        return 0

    if args.diff_file:
        with open(args.diff_file, encoding="utf-8") as fh:
            diff_text = fh.read()
    else:
        diff_text = pr_diff(args.pr, args.repo)
    diff_files = parse_diff(diff_text)
    payload, unanchored = build_review(findings, summary, diff_files, head_sha, event=event)

    prior_reviews: list[dict] = []
    if not offline and args.on_existing != "add":
        login = current_login()
        if login is None:
            print(unknown_login_warning("superseding"), file=sys.stderr)
        else:
            prior_reviews = find_prior_reviews(
                gh_json("api", "--paginate",
                        f"repos/{owner_repo}/pulls/{args.pr}/reviews"), login)

    print(f"PR: {url} @ {head_sha[:10]}", file=sys.stderr)
    print(f"verdict: {verdict or 'unknown'} -> review event {event}", file=sys.stderr)
    print(f"inline comments: {len(payload['comments'])}; in body only: {len(unanchored)}",
          file=sys.stderr)
    for f in unanchored:
        print(f"  not anchorable: [{f['id']}] {f['path']}:{f['line']}", file=sys.stderr)
    if prior_reviews:
        ids = ", ".join(str(r.get("id")) for r in prior_reviews)
        print(f"earlier reviews from this tool: {ids} ({args.on_existing})", file=sys.stderr)

    if prior_reviews and args.on_existing == "skip":
        print("nothing posted (--on-existing skip)", file=sys.stderr)
        return 0

    if args.dry_run:
        print(json.dumps(payload, indent=2))
        return 0

    if prior_reviews:
        supersede_reviews(owner_repo, args.pr, prior_reviews)

    result = post_review_with_fallbacks(owner_repo, args.pr, payload, findings,
                                        summary, head_sha)
    print(result.get("html_url", url))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (RuntimeError, ValueError, OSError, json.JSONDecodeError) as exc:
        print(f"post-review: {exc}", file=sys.stderr)
        sys.exit(1)
